if SERVER then return end

RARELOAD = RARELOAD or {}

function RARELOAD.RegisterFonts()
    surface.CreateFont("RareloadEditor", {
        font = "Consolas",
        size = 22,
        weight = 500,
        antialias = true,
        additive = false,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = true,
        blursize = 0,
        scanlines = 0,
        extended = true
    })
    surface.CreateFont("RareloadEditorSmall", {
        font = "Consolas",
        size = 18,
        weight = 400,
        antialias = true,
        additive = false,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = true,
        blursize = 0,
        scanlines = 0,
        extended = true
    })
    surface.CreateFont("RareloadDisplay", {
        font = "Segoe UI",
        size = 38,
        weight = 700,
        antialias = true,
        extended = true,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = true,
        additive = false,
        blursize = 0,
        scanlines = 0
    })
    surface.CreateFont("RareloadHeading", {
        font = "Segoe UI",
        size = 26,
        weight = 600,
        antialias = true,
        extended = true,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = true,
        additive = false,
        blursize = 0,
        scanlines = 0
    })
    surface.CreateFont("RareloadSubheading", {
        font = "Segoe UI",
        size = 20,
        weight = 500,
        antialias = true,
        extended = true,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = true,
        additive = false,
        blursize = 0,
        scanlines = 0
    })
    surface.CreateFont("RareloadBody", {
        font = "Segoe UI",
        size = 16,
        weight = 400,
        antialias = true,
        extended = true,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = true,
        additive = false,
        blursize = 0,
        scanlines = 0
    })
    surface.CreateFont("RareloadCaption", {
        font = "Segoe UI",
        size = 13,
        weight = 400,
        antialias = true,
        extended = true,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = true,
        additive = false,
        blursize = 0,
        scanlines = 0
    })
    surface.CreateFont("RareloadLabel", {
        font = "Segoe UI",
        size = 14,
        weight = 500,
        antialias = true,
        extended = true,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = true,
        additive = false,
        blursize = 0,
        scanlines = 0
    })
    surface.CreateFont("RareloadHeader", {
        font = "Segoe UI",
        size = 24,
        weight = 600,
        antialias = true,
        extended = true,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = true,
        additive = false,
        blursize = 0,
        scanlines = 0
    })
    surface.CreateFont("RareloadTitle", {
        font = "Segoe UI",
        size = 30,
        weight = 700,
        antialias = true,
        extended = true,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = true,
        additive = false,
        blursize = 0,
        scanlines = 0
    })
    surface.CreateFont("RareloadText", {
        font = "Segoe UI",
        size = 17,
        weight = 400,
        antialias = true,
        extended = true,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = true,
        additive = false,
        blursize = 0,
        scanlines = 0
    })
    surface.CreateFont("RareloadSmall", {
        font = "Segoe UI",
        size = 13,
        weight = 400,
        antialias = true,
        extended = true,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = true,
        additive = false,
        blursize = 0,
        scanlines = 0
    })
    surface.CreateFont("CTNV", {
        font = "Segoe UI",
        size = 19,
        weight = 500,
        antialias = true,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = true,
        additive = false,
        blursize = 0,
        scanlines = 0,
        extended = true
    })
    surface.CreateFont("CTNV2", {
        font = "Segoe UI",
        size = 26,
        weight = 700,
        antialias = true,
        shadow = true,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        additive = false,
        blursize = 0,
        scanlines = 0,
        extended = true
    })
    surface.CreateFont("RareloadUI.Title", {
        font = "Segoe UI",
        size = 30,
        weight = 600,
        antialias = true,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = true,
        additive = false,
        blursize = 0,
        scanlines = 0,
        extended = true
    })
    surface.CreateFont("RareloadUI.Heading", {
        font = "Segoe UI",
        size = 24,
        weight = 600,
        antialias = true,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = true,
        additive = false,
        blursize = 0,
        scanlines = 0,
        extended = true
    })
    surface.CreateFont("RareloadUI.Text", {
        font = "Segoe UI",
        size = 19,
        weight = 400,
        antialias = true,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = true,
        additive = false,
        blursize = 0,
        scanlines = 0,
        extended = true
    })
    surface.CreateFont("RareloadUI.Small", {
        font = "Segoe UI",
        size = 17,
        weight = 400,
        antialias = true,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = true,
        additive = false,
        blursize = 0,
        scanlines = 0,
        extended = true
    })
    surface.CreateFont("RareloadUI.Button", {
        font = "Segoe UI",
        size = 19,
        weight = 600,
        antialias = true,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = true,
        additive = false,
        blursize = 0,
        scanlines = 0,
        extended = true
    })
    surface.CreateFont("Bandal", {
        font = "Segoe UI",
        size = 18,
        weight = 500,
        antialias = true,
        outline = false,
        underline = false,
        italic = false,
        strikeout = false,
        symbol = false,
        rotary = false,
        shadow = false,
        additive = false,
        blursize = 0,
        scanlines = 0,
        extended = true
    })
end
